all the functions has successfully tested
elnurastanov/basicTestLesson pull request #13
Opened 2023-05-22 05:35 UTC by faridguluzade

2023-05-22 05:36 UTC, faridguluzade commented
I have done!

2023-05-22 05:40 UTC, elnurastanov requested changes

2023-05-22 05:40 UTC, elnurastanov commented on elnur.test.js
Undo this file

2023-05-22 05:40 UTC, elnurastanov requested changes

2023-05-22 05:40 UTC, elnurastanov commented on farid.test.js
> +// Test isEven function
Remove description comments

2023-05-22 05:42 UTC, elnurastanov commented on farid.test.js
> +  it("should throw error in different argument type", () => {
Duplicated test case

2023-05-22 05:43 UTC, elnurastanov commented on farid.test.js
> +  it("should return contry currency the case of the argument ", () => {
Where is naot found case?

2023-05-23 05:55 UTC, elnurastanov approved these changes

2023-05-23 05:55 UTC, merged