Miri test
elnurastanov/basicTestLesson pull request #6
Opened 2023-05-19 10:44 UTC by mirafgan

2023-05-19 10:45 UTC, mirafgan commented
index.js faylında commentimə baxarsız zəhmət olmasa

2023-05-22 06:25 UTC, elnurastanov requested changes

2023-05-22 06:25 UTC, elnurastanov commented on miri.test.js
> +    //index.js faylında commentimə baxın zəhmət olmasa
Remove commented codes

2023-05-22 06:25 UTC, elnurastanov commented on miri.test.js
> +//testStatement
Remove title comments

2023-05-23 05:57 UTC, elnurastanov approved these changes

2023-05-23 05:57 UTC, merged