amir.test.js file was added and testing was completed
elnurastanov/basicTestLesson pull request #9
Opened 2023-05-20 15:23 UTC by amirmammadov

2023-05-21 07:12 UTC, elnurastanov requested changes

2023-05-21 07:12 UTC, elnurastanov commented on index.js
Revert changes for this file

2023-05-21 07:12 UTC, elnurastanov commented on elnur.test.js
Undo deletion for this file

2023-05-21 09:58 UTC, amirmammadov commented
I did them

On Sun, 21 May 2023 at 11:12, Elnur Astanov ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> On index.js
> <https://github.com/elnurastanov/basicTestLesson/pull/9#discussion_r1199709980>
> :
>
> Revert changes for this file
> ------------------------------
>
> On elnur.test.js
> <https://github.com/elnurastanov/basicTestLesson/pull/9#discussion_r1199710077>
> :
>
> Undo deletion for this file
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/elnurastanov/basicTestLesson/pull/9#pullrequestreview-1435483727>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2MJQX223PTGUJ3QGB63PVDXHG56RANCNFSM6AAAAAAYIZO7J4>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2023-05-23 05:46 UTC, elnurastanov requested changes

2023-05-23 05:46 UTC, elnurastanov commented on amir.test.js
> +  });
Where is not found case?

2023-05-23 06:00 UTC, elnurastanov approved these changes

2023-05-23 06:00 UTC, merged